trigger: none  # Trigger on changes to the 'main' branch (adjust as needed)

pool:
  vmImage: 'ubuntu-latest'  # Select the appropriate image for your environment

variables:
  pythonVersion: '3.x'  # Python version to be used

jobs:
  - job: BuildAndAnalyzeLogs
    displayName: 'Run Log Analysis Script'
    steps:
      # Step 1: Checkout the repository
      - task: Checkout@1

      # Step 2: Set up Python environment
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(pythonVersion)
          addToPath: true

      # Step 3: Install required dependencies (langchain, langgraph, requests)
      - script: |
          python -m pip install --upgrade pip
          pip install langchain langgraph requests
        displayName: 'Install dependencies'

      # Step 4: Download and run the Python log analysis script
      - script: |
          python log_analysis_script.py
        displayName: 'Run Python Log Analysis Script'
