apimServiceName: api-prod-aj
namedValues:
loggers:
diagnostics:
backends:
apis:
  - name: test
    properties:
      serviceUrl: https://bing.com
  
  - name: demo
    properties:
      serviceUrl: https://google.com
